### ISSUE TITLE
Unable to create the Super App from scratch.

### ISSUE THREAD

**Issue by maneios** [callstack/super-app-example#3]
I attempted to create a super app from scratch, similar to the sample provided, but I couldn't proceed because of a few challenges.

The steps required to create the super app project from scratch were not listed in any of the callstack documents. 

It would be helpful if you could share the steps for creating the super app project structure (in the main branch) from scratch.

**Comment by jbroma** [comment]
Hey @maneios,

The setup shown here on the main branch is a simple monorepo with 2 react-native apps inside of it. 

Essentially all there is to it is: 
- creating new project directory, 
- running `yarn init`, 
- creating `packages` directory
- configuring the top level `package.json` similarly to what's shown here, 
- then creating 2 RN apps in packages directory using `npx react-native init`
